#!/usr/bin/env bash

set -o errexit
set -o pipefail

SPACELIFT_PROFILE="fidelusaleksander"
SPACELIFT_STACK_ID="spacelift-infrastructure"

function spacelift:login {
	# Login to spacelift

	spacectl profile select "$SPACELIFT_PROFILE"
	spacectl profile login \
		--method browser \
		--endpoint "https://$SPACELIFT_PROFILE.app.spacelift.io/" \
		"$SPACELIFT_PROFILE"
}

function spacelift:preview {
	# Run terraform plan locally to check local changes

	cd infra
	spacectl stack local-preview --id "$SPACELIFT_STACK_ID"
	cd -
}

function test {

	tests=$(find . -type f -regex '.*-test\.rego$')
	for test in $tests; do
		opa test -v $test ${test/-test.rego/.rego}
		echo
	done
}

function fmt {
	opa fmt --write policies/
}

function help {
	printf "%s <task> [args]\n\nTasks:\n" "${0}"
	compgen -A function | grep -v "^_" | cat -n
	printf "\nExtended help:\n  Each task has comments for general usage\n"
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
